[myservers]
server1-i4c ansible_host=server1-i4c ansible_user=root ansible_ssh_pass=P@ssw0rd1 ansible_port=22 ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'